# Generated by Django 4.2.13 on 2024-11-13 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_experiencie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workeperiencies',
            old_name='archivement',
            new_name='location',
        ),
    ]
