# Generated by Django 4.2.13 on 2024-11-13 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_experiencie', '0002_rename_archivement_workeperiencies_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workeperiencies',
            old_name='end_data',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='workeperiencies',
            old_name='star_data',
            new_name='star_date',
        ),
    ]
