# Generated by Django 4.2.13 on 2024-11-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_experiencie', '0003_rename_end_data_workeperiencies_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workeperiencies',
            old_name='star_date',
            new_name='start_date',
        ),
    ]
