# Generated by Django 4.2.13 on 2024-11-13 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('work_experiencie', '0003_rename_end_data_workeperiencies_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkExperienciesArchivements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('work_experiencies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiencies_archivements', to='work_experiencie.workeperiencies')),
            ],
        ),
    ]
