# Generated by Django 4.2.13 on 2024-11-12 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='end_data',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='star_data',
            new_name='start_date',
        ),
    ]
