# Generated by Django 4.2.13 on 2024-11-12 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('header', '0003_alter_header_posted_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinksHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(default='')),
                ('icon', models.URLField(default='')),
                ('url', models.TextField(default='')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='header.header')),
            ],
        ),
    ]
