# Generated by Django 4.2.13 on 2024-11-12 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linksHeader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linksheader',
            old_name='url',
            new_name='link',
        ),
    ]
