# Generated by Django 4.2.13 on 2024-11-12 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('header', '0002_remove_header_links_header_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='posted_by',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='header', to=settings.AUTH_USER_MODEL),
        ),
    ]
